Introducing Profile Name Parameter and Dockerfile Improvement
w4af/w4af pull request #615
Opened 2023-09-04 02:26 UTC by cferreirasuazo

Dear w4af Community,

I am excited to present my latest contribution to the w4af project that brings enhanced usability and eliminates a warning in our Dockerfile. This PR introduces a new feature that allows users to pass a profile name as a parameter to the API, streamlining the workflow and enhancing flexibility. Additionally, I've addressed the TRACEMALLOC warning by adding PYTHONTRACEMALLOC in the Dockerfile.

**Changes Included in this PR:**

1. **Profile Name Parameter Addition:**

    I've implemented a way to pass a profile name as a parameter to the API, eliminating the need to pass the content of the profile name. This enhancement simplifies the API usage and provides users with a more intuitive and user-friendly experience.

2. **Dockerfile Improvement:**

    I've resolved the TRACEMALLOC warning issue by adding the PYTHONTRACEMALLOC environment variable to the Dockerfile. This improvement ensures that w4af runs smoothly in Docker containers without generating unnecessary warnings.

**How to Use the Profile Name Parameter:**

I implemented a 2 steps validation. First, check if the parameter of the scan_profile is a file name, second validate if the profile file exists, then the module does the rest in processing the scanning.

 curl -k -H "Content-Type: application/json" --location 'https://localhost:5000/scans/' \   
--data '{
    "target_urls": ["your_target_url"],
    "scan_profile": "OWASP_TOP10.pw4af"
}

your feedback is welcome in order to improve this PR and next improvements.

2023-09-04 18:39 UTC, cferreirasuazo commented
Hello @security-companion , I was working on a support branch suggested by one of the contributors of the project. I will close this PR and create a new one using my changes and omitting the dependencies check changes.

2023-09-04 19:48 UTC, cferreirasuazo commented
Hello @security-companion , 

Thanks for the feedback. 

When learning about the project, I had some trouble running it because of some dependencies., so I visited the issues page of the project in order to find a solution . So I found this [conversation](https://github.com/w4af/w4af/issues/587)  and this [changes](https://github.com/codders/w4af/tree/feat/w4af_api-support]). and the allowed me to run the project.

2023-09-05 06:32 UTC, security-companion commented
Hi,
I made a commit on the main branch and the same test failed. So it seems that failure was not caused by your changes.
@codders
Do you know why the test fails?
Are you still planning to merge the changes from https://github.com/codders/w4af/tree/feat/w4af_api-support into this repo?
Greetings

2023-09-06 08:30 UTC, codders commented
Hi @security-companion,

I've created #623 to address the failing test-case. Looks like a change in the output from Retirejs.

2023-09-06 08:35 UTC, codders requested changes
Thanks for the great feature add - this looks like it will make life a lot easier for API users!

2023-09-06 08:35 UTC, codders commented on w4af/core/ui/api/utils/scans.py
> +    print("***************create_temp_profile*********************")
Please don't put `print` statements in production code. It's fine if you need them for debugging, but anything that should go to the user should be directed through the `OutputManager` (`om.out.debug(msg)`).

2023-09-06 08:35 UTC, codders commented on w4af/plugins/tests/grep/test_retirejs.py
> + - jQuery 1.x and 2.x are End-of-Life and no longer receiving security updates
My pull request #623 hopefully addresses this issue, so you don't need to make this change. As @security-companion says, it's helpful if pull requests address one issue at a time (and not multiple issues in the same PR).

2023-09-06 08:35 UTC, codders commented on extras/docker/Dockerfile
> +FROM python:3.11-slim as base
I would also agree with @security-companion here that the Docker and `dependency_check` changes belong in a separate PR.

2023-09-06 14:08 UTC, cferreirasuazo commented
as suggested by @codders, I will create multiple PRs. I will close this one. and Send a PR with the Docker update and my change with the profile file.

2023-09-06 14:18 UTC, closed without merging

2023-09-12 07:33 UTC, codders commented
Hi @cferreirasuazo,

I see you closed this, but I haven't yet seen the new PR for the feature. We would love to have the profile name parameter feature integrated, and that should resolve #592.

If you need help with making the new / clean PR, please let me know!

2023-09-12 20:47 UTC, cferreirasuazo commented
@codders hey, here is the new PR